version: "3"
services:
  postgres:
    container_name: nest_init_dev
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

